apiVersion: v1
kind: Namespace
metadata:
  name: m2m-rsp-zone-a
  labels:
    zone: zone-a
    app: m2m-rsp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: m2m-rsp-config
  namespace: m2m-rsp-zone-a
data:
  ZONE_NAME: "zone-a"
  ZONE_REGION: "us-east-1"
  LOG_LEVEL: "INFO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2m-rsp-server
  namespace: m2m-rsp-zone-a
  labels:
    app: m2m-rsp
    zone: zone-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: m2m-rsp
      zone: zone-a
  template:
    metadata:
      labels:
        app: m2m-rsp
        zone: zone-a
    spec:
      containers:
      - name: m2m-rsp-mock
        image: m2m-rsp-mock:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: ZONE_NAME
          valueFrom:
            configMapKeyRef:
              name: m2m-rsp-config
              key: ZONE_NAME
        - name: ZONE_REGION
          valueFrom:
            configMapKeyRef:
              name: m2m-rsp-config
              key: ZONE_REGION
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /status/smdp
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status/smdp
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: m2m-rsp-service
  namespace: m2m-rsp-zone-a
  labels:
    app: m2m-rsp
    zone: zone-a
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: m2m-rsp
    zone: zone-a
---
apiVersion: v1
kind: Service
metadata:
  name: m2m-rsp-nodeport
  namespace: m2m-rsp-zone-a
  labels:
    app: m2m-rsp
    zone: zone-a
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: m2m-rsp
    zone: zone-a